### PR TITLE
Fix attendance date validation

### LINKED ISSUE #123: [PE-D] Attendance date not shown correctly when input date is invalid
Input: attend 2 d/31/06/2020
output: marked attendance on 01/07/2020

other examples:

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: WM71811/ped#12

### PR DESCRIPTION
**Pull request by rnmy**
Closes #123 

Previous implementation allowed dates like 30/02/2020 and 31/06/2020 to pass.

### CODE REVIEW

**Review by kwannoel — APPROVED** [review]

File: src/main/java/seedu/address/model/attendance/Attendance.java [hunk 1]
```diff
@@ -21,7 +22,8 @@
             + "Month should be 01-12"
             + "\n"
             + "Year should be a 4 digit numeric value, with the exception of 0000";
-    private static final DateTimeFormatter DATE_FORMAT = DateTimeFormatter.ofPattern("dd/MM/yyyy");
+    private static final DateTimeFormatter DATE_FORMAT = DateTimeFormatter.ofPattern("dd/MM/uuuu")
```
Comment (chrisgzf) [inline src/main/java/seedu/address/model/attendance/Attendance.java:25]: Cool change! Went to read up on it and TIL apparently using `uuuu` is better than using `yyyy`.

**Review by chrisgzf — APPROVED** [review]
LGTM!
