### PR TITLE
Invalid parameter tags

### LINKED ISSUE #153: Return the incorrectly formatted portion in the output
Closes #109
Closes #104 
Closes #112

For example:
`add n/Betsy Crowe tg/friend e/betsycrowe@example.com t/betsy_crowe m/A0201234C a/Newgate Avenue p/1234567 tg/groupmate`

is invalid, because it treats `A0201234C a/Newgate Avenue` as a `matricNumber`, since it ignores `a/`.

We should be explicit by giving users this information, so that they know `a/` is taken literally.

### PR DESCRIPTION
**Pull request by kwannoel**
- Reduce test debt
- Return expressive error messages.

Closes #153

### CODE REVIEW

File: src/main/java/seedu/address/logic/parser/ParserUtil.java [hunk 1]
```diff
@@ -149,8 +149,16 @@ public static Attendance parseAttendance(String input) throws ParseException {
         try {
             return Attendance.fromDateString(input);
         } catch (IllegalArgumentException e) {
-            throw new ParseException(Attendance.MESSAGE_CONSTRAINTS);
+            throw parseException(input, Attendance.MESSAGE_CONSTRAINTS);
         }
     }
 
+    private static String inputIsWrong(String input, String message) {
```
Comment (Rishi5154) [inline src/main/java/seedu/address/logic/parser/ParserUtil.java]: Want to consider renaming the method name, to sound more like an actionable verb i.e `returnsWrongInput`? Just to match the current code quality standards at https://se-education.org/guides/conventions/java/basic.html#naming

File: src/main/java/seedu/address/logic/parser/ParserUtil.java [hunk 2]
```diff
@@ -149,8 +149,16 @@ public static Attendance parseAttendance(String input) throws ParseException {
...
+        return "Your input: \"" + input + "\" is incorrectly formatted.\n"
+                + "See below for further details:\n\n" + message;
+    }
+
+    private static ParseException parseException(String input, String message) {
+        return new ParseException(inputIsWrong(input, message));
```
Comment (Rishi5154) [inline src/main/java/seedu/address/logic/parser/ParserUtil.java]: Should this be `throw new ParseException?`Not that its a problem, usually thought we throw exceptions.

Comment (kwannoel) [reply src/main/java/seedu/address/logic/parser/ParserUtil.java]: nah I want to keep the `throw` within each function to be explicit the functions throw exceptions.

Otherwise it won't be apparent where the exception occurs, as you can see below:
```
    public static Attendance parseAttendance(String input) throws ParseException {
        requireNonNull(input);
        try {
            return Attendance.fromDateString(input);
        } catch (IllegalArgumentException e) {
            parseException(input, Attendance.MESSAGE_CONSTRAINTS);
        }
    }
```

**Review by chrisgzf — APPROVED** [review]
Love this change! The messages will now be more descriptive!
